services:
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=examplepw
      - MYSQL_DATABASE=SongRex
    volumes:
      - ./mysql-db:/var/lib/mysql

  server:
    container_name: songrex-server
    restart: unless-stopped
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=examplepw
      - MYSQL_DATABASE=SongRex
      - SECRET_KEY=examplekey
    build: server
    depends_on:
      - mysql

  web:
    container_name: songrex-web
    restart: unless-stopped
    environment:
      - PORT=5173
      - ORIGIN=<URL>
    build: web
    ports:
      - 5173:5173
    depends_on:
      - server
