services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=examplepw
      - MYSQL_DATABASE=SongRex
    networks:
      - shared-network
    volumes:
      - ./mysql-db:/var/lib/mysql

  server:
    container_name: songrex-server
    restart: unless-stopped
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=examplepw
      - MYSQL_DATABASE=SongRex
      - SECRET_KEY=examplekey
    build: server
    networks:
      - shared-network
    depends_on:
      - mysql

  web:
    container_name: songrex-web
    restart: unless-stopped
    build: web
    ports:
      - 5173:5173
    networks:
      - shared-network
    depends_on:
      - server

networks:
  shared-network: