services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=examplepw
      - MYSQL_DATABASE=SongRex
    volumes:
      - ./sql-db:/var/lib/mariadb

  server:
    container_name: songrex-server
    restart: unless-stopped
    environment:
      - PUBLIC_URL=http://exampleurl.com:port
      - ADMIN_PASSWORD=examplepw
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=examplepw
      - MYSQL_DATABASE=exampledb
      - SECRET_KEY=examplekey
      - X_FORWARD_ENABLED=false
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mariadb